apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms -Xmx
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: es-cluster
        - name: http.host
          value: 0.0.0.0
        - name: http.port
          value: "9200"
        - name: node.name
          value: es-node-1
        - name: path.data
          value: /tmp/mnt/elastic/data
        - name: transport.host
          value: 127.0.0.1
        image: 'docker.elastic.co/elasticsearch/elasticsearch:'
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - -f
            - -u
            - 'elastic:'
            - http://localhost:9200/_cat/health
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
      hostname: elasticsearch
      restartPolicy: Always
status: {}
