apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: express
  name: express
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: express
    spec:
      containers:
      - env:
        - name: APIKEY
        image: express-server
        name: express-server-container
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /app/node_modules
          name: express-claim0
        - mountPath: /app
          name: express-claim1
        - mountPath: /app/InputOutput
          name: express-claim2
      restartPolicy: Always
      volumes:
      - name: express-claim0
        persistentVolumeClaim:
          claimName: express-claim0
      - name: express-claim1
        persistentVolumeClaim:
          claimName: express-claim1
      - name: express-claim2
        persistentVolumeClaim:
          claimName: express-claim2
status: {}
